### ISSUE TITLE
App crash with Orbot not running

### ISSUE THREAD

**Issue by robovoice1** [accrescent/accrescent#412]
```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024010400:user/release-keys
package: app.accrescent.client:39
process: app.accrescent.client
processUptime: 1190 + 190 ms
installer: app.accrescent.client

javax.net.ssl.SSLHandshakeException: connection closed
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at b5.p.b(Unknown Source:16)
	at b5.t.k(Unknown Source:19)
	at g7.a.p(Unknown Source:7)
	at y7.g0.run(Unknown Source:114)
	at i.h.run(Unknown Source:12)
	at e8.i.run(Unknown Source:2)
	at e8.a.run(Unknown Source:91)
	Suppressed: d8.g: [p1{Cancelling}@4d4a43d, Dispatchers.Main.immediate]
Caused by: java.io.EOFException: connection closed
	... 21 more


```

![Screenshot_20240109-150337](https://github.com/accrescent/accrescent/assets/92784377/2b13bee9-e8b2-42a8-99aa-6a60a069ed7e)

Google Pixel  6 pro 
UQ1A.240105.002.2024010400

I used Rethink DNS and routed all traffic through Orbot, on the second try to update the app crashed .

**Comment by ghost** [comment]
- Pixel 5 GrapheneOS 2024121500
- Orbot 17.3.2 RC 1 (tor 0.4.8.12)
- Accrescent 25.0

I could not reproduce this issue.
I installed Orbot and turned on the killswitch, when Orbot was disabled it would start.
Also when connected to Orbot or when Orbot was not set-up.
Maybe @robovoice1 couls try again with updated apps?

**Comment by robovoice1** [comment]
No more crashes of the app
and a message for the user:
![IMG_20241222_135724](https://github.com/user-attachments/assets/e0bb016b-8ddf-4c28-b1fc-4c507007b97d)

closing this issue 😃
