### ISSUE TITLE
App crash with device in airplane mode and manually checking for updates

### ISSUE THREAD

**Issue by robovoice1** [accrescent/accrescent#425]
```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024012600:user/release-keys
package: app.accrescent.client:40
process: app.accrescent.client
processUptime: 2201 + 202 ms
installer: app.accrescent.client

javax.net.ssl.SSLHandshakeException: connection closed
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
	at z8.l.g(Unknown Source:105)
	at z8.l.c(Unknown Source:173)
	at z8.f.a(Unknown Source:730)
	at z8.a.a(Unknown Source:59)
	at a9.f.b(Unknown Source:123)
	at x8.b.a(Unknown Source:970)
	at a9.f.b(Unknown Source:123)
	at a9.a.a(Unknown Source:100)
	at a9.f.b(Unknown Source:123)
	at a9.g.a(Unknown Source:148)
	at a9.f.b(Unknown Source:123)
	at z8.j.g(Unknown Source:95)
	at z8.j.e(Unknown Source:41)
	at i5.p.a(Unknown Source:95)
	at i5.t.j(Unknown Source:19)
	at o7.a.m(Unknown Source:7)
	at g8.g0.run(Unknown Source:114)
	at k.h.run(Unknown Source:12)
	at m8.i.run(Unknown Source:2)
	at m8.a.run(Unknown Source:91)
	Suppressed: l8.g: [o1{Cancelling}@e88c601, Dispatchers.Main.immediate]
Caused by: java.io.EOFException: connection closed
	... 22 more
```

Device was in airplane mode and i tried to manually check for updates (by swiping down)
on the first try app closes
on the second try crash report

**Comment by PatrykMis** [comment]
@lberrymage  probably #322 will fix this, too.

**Comment by robovoice1** [comment]
Proposal:
Some kind of feedback/info message for the user.

For example with the app FFupdater you can swipe down as much as you want (no crash),  but also gives a message at the bottom: internet connection temporaly not avaiable, try again later, when user is in airplane mode/ no internet and swiping down.

**Comment by robovoice1** [comment]
No more crashes  and additional message appears
Thanks 😃👍

**Comment by lberrymage** [comment]
Reopening since no changes were made to fix this issue, so it probably still exists.
